name: reg_it_abstract
description: "Complex abstraction for an implementation of DI Container."
version: 1.0.0
homepage:
repository: https://github.com/dronn1k-org/reg_it_abstract

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  meta: ^1.16.0

dev_dependencies:
  test: ^1.25.14
  lints: ^5.1.1